[Autodelivery] update Foreign pull request pipeline for Java 8 projects from DanySK/centralized-automated-deployer@6b8263b

diff --git a/.github/workflows/build-external-pull-requests.yml b/.github/workflows/build-external-pull-requests.yml
--- a/.github/workflows/build-external-pull-requests.yml
+++ b/.github/workflows/build-external-pull-requests.yml
@@ -16,4 +16,20 @@ jobs:
           java-version: ${{ matrix.jvm_version }}
       - uses: actions/checkout@v2
       - shell: bash 
-        run: ./gradlew check
+        run: |
+          if [ -x 'build.sh' ]
+          then
+            echo 'Detected custom build instructions'
+            ./build.sh
+          elif [ -x 'gradlew' ]
+          then
+            echo 'Detected gradle wrapper, running ./gradlew clean check --parallel'
+            ./gradlew clean check --parallel
+          elif [ -f 'pom.xml' ]
+          then
+            echo 'Detected Maven pom.xml, running mvn clean install'
+            mvn clean install
+          else
+            echo 'No valid configuration detected, failing'
+            exit 1
+          fi
